name: Report gas diff

on:
  push:
    branches:
      - main
  pull_request:
    branches: [develop, staging, main]

jobs:
  compare_gas_reports:
    runs-on: ubuntu-latest
    env:
      FORK_FROM_BLOCK_NUMBER_MAINNET: "16426621"
      FORKING_NETWORK: "MAINNET"
      FORGE_API_KEY_ETHEREUM: ${{ secrets.FORGE_API_KEY_ETHEREUM }}
      MAINNET_RPC_URL: ${{ secrets.ETHEREUM_RPC_URL }}
      GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
      MNEMONIC: ${{ secrets.MNEMONIC }}
      MAINNET_PRIVATE_KEY: ${{ secrets.MAINNET_PRIVATE_KEY }}
      TESTNET_PRIVATE_KEY: ${{ secrets.TESTNET_PRIVATE_KEY }}
      MAINNET_RPC_URL_POLYGON: ${{ secrets.MAINNET_RPC_URL_POLYGON }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      BSC_RPC_URL: ${{ secrets.FORGE_API_KEY_BSC }}
      FORK_FROM_BLOCK_NUMBER_BSC: ${{ secrets.FORK_FROM_BLOCK_NUMBER_BSC }}
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      # Add any step generating a gas report to a temporary file named gasreport.ansi. For example:
      - name: Run tests
        run: yarn test-forge-ci --gas-report > gasreport.ansi # <- this file name should be unique in your repository!

      - name: Compare gas reports
        uses: Rubilmax/foundry-gas-diff@v3.14
        with:
          sortCriteria: avg,max # sort diff rows by criteria
          sortOrders: desc,asc # and directions
        id: gas_diff

      - name: Add gas diff to sticky comment
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          delete: ${{ !steps.gas_diff.outputs.markdown }}
          message: ${{ steps.gas_diff.outputs.markdown }}